name = "RiFyFi"
uuid = "15fa5781-021b-46e5-a995-4fbf9d615b14"
authors = ["Alice Chillet <alice.chillet@irisa.fr> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
